name = "constructible-universe"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["ConstructibleUniverse"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a ↦ b`
autoImplicit = false
relaxedAutoImplicit = false
weak.linter.mathlibStandardSet = true
maxSynthPendingDepth = 3

[[require]]
name = "mathlib"
scope = "leanprover-community"

[[lean_lib]]
name = "ForMathlib"

[[lean_lib]]
name = "FirstOrderZFC"

[[lean_lib]]
name = "ConstructibleUniverse"
